services:
  config-server:
    image: blackimage/banking-system-config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      # - GIT_USERNAME=your-github-username <--- add if the repo is private
      # - GIT_PASSWORD=your-personal-access-token
      - SPRING.CLOUD.CONFIG.SERVER.GIT.URI=https://github.com/en-atul/banking-system-config
    networks:
      - tracing

  naming-server:
    image: blackimage/banking-system-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    environment:
      - NODE_ENV=production
    networks:
      - tracing

  api-gateway:
    image: blackimage/banking-system-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      - NODE_ENV=production
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
    networks:
      - tracing

  # account-service:
  #   image: blackimage/banking-system-account-service:0.0.1-SNAPSHOT
  #   mem_limit: 700m
  #   ports:
  #     - "8100:8100"
  #   depends_on:
  #     - config-server
  #     - naming-server
  #   environment:
  #     - NODE_ENV=production
  #     - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
  #     - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
  #   networks:
  #     - tracing

  # auth-service:
  #   image: blackimage/banking-system-auth-service:0.0.1-SNAPSHOT
  #   mem_limit: 700m
  #   ports:
  #     - "8200:8200"
  #   depends_on:
  #     - config-server
  #     - naming-server
  #   environment:
  #     - NODE_ENV=production
  #     - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
  #     - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
  #   networks:
  #     - tracing

  # customer-service:
  #   image: blackimage/banking-system-customer-service:0.0.1-SNAPSHOT
  #   mem_limit: 700m
  #   ports:
  #     - "8300:8300"
  #   depends_on:
  #     - config-server
  #     - naming-server
  #   environment:
  #     - NODE_ENV=production
  #     - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
  #     - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
  #   networks:
  #     - tracing

  # ledger-service:
  #   image: blackimage/banking-system-ledger-service:0.0.1-SNAPSHOT
  #   mem_limit: 700m
  #   ports:
  #     - "8400:8400"
  #   depends_on:
  #     - config-server
  #     - naming-server
  #   environment:
  #     - NODE_ENV=production
  #     - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
  #     - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
  #   networks:
  #     - tracing

  # notification-service:
  #   image: blackimage/banking-system-notification-service:0.0.1-SNAPSHOT
  #   mem_limit: 700m
  #   ports:
  #     - "8500:8500"
  #   depends_on:
  #     - config-server
  #     - naming-server
  #   environment:
  #     - NODE_ENV=production
  #     - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
  #     - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
  #   networks:
  #     - tracing

  # transaction-service:
  #   image: blackimage/banking-system-transaction-service:0.0.1-SNAPSHOT
  #   mem_limit: 700m
  #   ports:
  #     - "8600:8600"
  #   depends_on:
  #     - config-server
  #     - naming-server
  #   environment:
  #     - NODE_ENV=production
  #     - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
  #     - SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
  #   networks:
  #     - tracing

networks:
  tracing:
    driver: bridge
