services:
  db:
    container_name: banking-system-jpa-postgres
    image: postgres
    environment:
      POSTGRES_USER: banking-system
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking-system
    ports:
      - "5336:5432"
    restart: unless-stopped
    volumes:
      - db:/data/postgres
    networks:
      - tracing

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db    

volumes:
  db:
  mongo-data:

networks:
  tracing:
    driver: bridge
